Netflix/spectator-js

.jscsrc
src/counter.js
src/gauge.js
src/http.js
src/meter_id.js
src/percentile_buckets.js
src/percentile_timer.js
src/timer.js
test/meter_id.test.js
test/percentile_buckets.test.js
test/percentile_timer.test.js
test/registry.test.js

Adds support for percentile timers: timers that bucket the counts for
different durations in order to allow estimating percentiles.

Add support for percentile timers

---

.travis.yml
README.md
package-lock.json
package.json

Attempt to use the travis-deploy-once module to only upload codecov
reports once. Add a nice badge to display our current coverage

Upload code coverage reports once

---

src/bucket_counter.js
src/bucket_dist_summary.js
src/bucket_functions.js
src/bucket_timer.js
test/bucket_counter.test.js
test/bucket_dist_summary.test.js
test/bucket_functions.test.js
test/bucket_timer.test.js

* `BucketTimer`: A timer that manages a set of timers that get updated
based on the bucket function supplied.
* `BucketCounter`: A distribution summary that manages a set a counters
that will be updated based on the bucket function supplied.
* `BucketDistributionSummary`: A distribution summary that manages a set
of distribution summaries that will be updated based on the bucket
function supplied.
A set of `BucketFunctions` is supplied:
* `age`: a function that maps ages to a set of buckets creating more
buckets towards the fresher end of the range.
* `ageBiasOld`: a function that maps ages to a set of buckets creating more
buckets towards the older end of the range.
* `latency`: a function that maps latencies to a set of buckets
creating more buckets towards the faster end of the range. …

Add Bucket Meters:

---

src/bucket_counter.js
src/bucket_dist_summary.js
src/bucket_timer.js
src/meter_id.js
src/percentile_buckets.js
src/percentile_dist_summary.js
src/percentile_timer.js
src/polled_meter.js
src/registry.js
test/bucket_counter.test.js
test/bucket_dist_summary.test.js
test/bucket_timer.test.js
test/meter_id.test.js
test/percentile_dist_summary.test.js
test/percentile_timer.test.js
test/polled_meter.test.js
test/registry.test.js

* Adds `monitorValue` to generate dynamic values for gauges
* Adds `monitorMonotonicNumer` to generate counter increments based on
monotonic values
To support this we also add a `strictMode` to the config to help
users catch errors during development by throwing when invalid
operations are attempted such as creating metrics with no names, or
empty keys/values as tags.

Support for PolledMeters

---

README.md
src/http.js
src/interval_counter.js
src/long_task_timer.js
src/nop_registry.js
src/polled_meter.js
src/registry.js
test/interval_counter.test.js

A counter that keeps track of its last update
This adds a couple of methods to the registry to facilitate testing. In
particular we add: `hrtime` so we can mock the clock, and
`schedulePeriodically` so we can ignore calls to `setInterval` done when
using dummy meters (those that are returned when an existing id in the
registry is of a different type)

Support IntervalCounter

---

README.md
src/counter.js
src/dist_summary.js
src/gauge.js
src/http.js
src/index.js
src/nop_registry.js
src/percentile_dist_summary.js
src/percentile_timer.js
src/polled_meter.js
src/registry.js
src/timer.js
test/api.test.js
test/bucket_counter.test.js
test/bucket_dist_summary.test.js
test/bucket_timer.test.js
test/counter.test.js
test/interval_counter.test.js
test/long_task_timer.test.js
test/percentile_dist_summary.test.js
test/percentile_timer.test.js
test/polled_meter.test.js
test/registry.test.js

* export the classes users are expected to interact with instead of just
one function to create a registry.
* rename `registry.newId` to `registry.createId` for consistency with
spectator-java.
* Fix `counter.increment(0)` - was doing the equivalent of
`counter.increment()` which adds 1 to the current count.
* Start documenting the API using JSDoc

API updates

---

src/registry.js
test/registry.test.js

Add support to enable/disable publishing of metrics based on a function
passed in the config to the registry: `isEnabled()` which will return a
boolean value indicating whether metrics should be published.

Hook for enabling/disabling publishing of metrics

---

package.json
src/percentile_buckets.js
src/registry.js

Add an isLevelEnabled and trace to the logger interface. This is
supported by pino, and other logging frameworks. If trace is enabled we
will dump the measurements sent to the aggregator, which can be very
useful for debugging.

Add trace and isLevelEnabled to the logger

---

package.json
src/logger.js
src/registry.js
test/logger.test.js

This makes it possible to configure the verbosity of the logging done by
this module by passing a config option to the registry: `logLevel` with
the desired logging level. For example for very verbose logging you
could pass `logLevel: 'trace'`. The default level is `'info'`

Add a simple configurable logger

---

package.json
src/percentile_dist_summary.js
src/percentile_timer.js

We were incorrectly generating the value for the percentile tags using
the lowercase hex string representation and it should have been upper
case

Percentile tag values should be uppercase

---

src/registry.js

Using `info` level in a log entry that is repeated every few seconds is flooding the logs with that message.

fix(registry): log sending metrics with debug level

---

package.json
src/registry.js
test/registry.test.js

Previously we were ignoring meters with unknown or missing statistic tag
values. Now we match the java/golang behavior of sending those as gauges
by default.

Use a gauge behavior for unknown statistics

---

src/gauge.js
src/registry.js
test/gauge.test.js
test/registry.test.js

Add a few deprecated aliases that help with migrating from atlasclient
to spectator-js

Add a few deprecated aliases to help with adoption

---

package-lock.json
package.json
src/http.js
src/publisher.js
src/registry.js
test/registry.test.js

On graceful shutdown we want make sure the last `_publish` triggered by `stop` succeeds (or fails) before we kill the process. Allowing custom publishers provides long term flexibility.
1) breaks out publisher, so it can be extended by implementations
2) adds `config.publisher` for a custom Publisher in registry
3) waits for optional callback in `registry.stop` and `publisher`
4) replace handcrafted http client with will maintained lean module
The test suit is very comprehensive and the only needed to add a test to check the error condition.
this commit adds two lean dependencies to spectator-js:
1) `needle` (lean http client that has a callback interface)
2) `async` to manage the partitioned async state of waiting for multiple async calls

feat: waits for last publishing before shutdown + expose publisher

---

src/publisher.js
test/registry.test.js

**Why?**
callback was not being called on stop if there were no metrics to flush or if spectator was disabled. This was causing NQ to graceful shutdown to fail with a timeout.
**How?**
consistently calling callback fix the issue. As per @hekike suggestion, a warning is issued if it can't flush metrics because spectator is disabled.

fix(publisher): consistent callback on sendMetricsNow

---

src/meter_id.js
src/registry.js

The canary we run on NQ showed a spike on CPU usage, I didn't find anything obvious, but I did find these possible performance improvements (without any functionality change).
Because of tags we have to create quite a few metrics per request, so if we can fetch the metric from the map without having to create a new metric first, it might render some (maybe minimal) improvements...

fix(performance): don't create objects when not needed

---

src/percentile_dist_summary.js
src/percentile_timer.js
src/polled_meter.js

Classes are not garbage collected by V8 (tested up to V8 7.6, Node.js
v12.10.0). V8 also will re-create a class every time the class
declaration code is executed. As a result, each time users call
PerformanceTimer.Builder we'll create a new class, which will be stored
on the heap and never collected, thus leading to a memory leak.
This commit moves the class declaration on all three places we were
using the static get class pattern to outside the function, ensuring we
only declare the class once. The commit also rename `Builder` classes
with a more descriptive name, to ensure diagnostic tools can distinguish
those three classes. The public API remains unchanged.

fix(performance): fix leak on static get methods

---

src/registry.js

Apparently the `concat` method is significantly slower than using
`push` repeatedly.
https://dev.to/uilicious/javascript-array-push-is-945x-faster-than-array-concat-1oki

Avoid the concat method in favor of push

---

.travis.yml
src/http.js
src/log_entry.js
test/http.test.js

Switch from the old spectator names, to the new IPC metric names:
https://netflix.github.io/spectator/en/latest/ext/ipc/

Use ipc metric names and retry 503 errors

---

src/http.js
src/publisher.js
test/http.test.js
test/polled_meter.test.js
test/publisher.test.js

This adds metrics to track the number of measurements sent and dropped
due to validation or network errors.
`spectator.measurements`:
* `id=sent`
* `id=dropped` `error=validation`
* `id=dropped` `error=http-error`
Using these new metrics our users could detect sudden behavior changes
as they test new releases, and their effect on metrics produced.

Add metrics to track measurements sent and dropped

---

src/http.js
src/log_entry.js

Plus remove unused ID in our http client now that we are using log_entry

Fix tag name in successful ipc calls

---

src/http.js
src/registry.js
test/http.test.js

Support a new config option: `connectOptions` a function that will be
called before making http(s) requests allowing the user to add
keys/certs, etc.

Add a hook for tweaking https connect options

---

package.json
src/publisher.js
test/publisher.test.js

If the server sends us a response that cannot be parsed as JSON ignore
it. Previously we would crash.

Ignore broken replies from the server

---

src/publisher.js
test/publisher.test.js

It seems `needle` is now parsing the response body and returning it as
an `object`. Handle the case where it's an object or the old behavior
where it's returned as a string

Http response body can be an object

---

.travis.yml
package-lock.json
package.json

Travis attempts to publish the module with the first version that
finishes building but now we need to have at least node 10 since the
version of npm bundled with node 6 does not include a prepare script.

Only publish using node 10

---

.travis.yml

The version of npm shipped with node 10 is too old. No `prepare` script
support

Deploy using node13

---

test-d/index.test-d.ts
types/registry.d.ts

Client allows for no config, the types should allow this also.

fix(types): allow optional config

---

package-lock.json
package.json
src/registry.js
test/api.test.js

Adds:
* intervalCounter
* bucketCounter
* bucketDistSummary
* bucketTimer
* percentileDistSummary
* percentileTimer
to the registry.
The main goal is to be able to easily migrate apps using the old
atlas-node-client which provided these methods.

Add to the registry percentile and bucket meters

---

src/registry.js

As we were investigating the recent increase in heap allocation after bumping to latest for this lib, it came down to this change: https://github.com/Netflix/spectator-js/pull/34
I was thinking that maybe pushing on the array (changing it's size) caused v8 to over allocate for the array, even if it does not end up getting used.  I thought maybe this might help, and if nothing else it should not hurt.  Additionally, I was thinking we could change from `.push` to index setting, but with performance things it can be surprising, so I figured I would start with this PR to change one small thing at a time.
Thoughts?

fix: pre-allocate meters array size

---

src/http.js

This log is VERY commonly hit and since it is retried it is not useful to users.  Downgrading to `debug` will easily let us turn it back on if we need to debug.
Ideally libraries will *never* log directly but instead expose interfaces for consumers to log off specific events.  While it would be a breaking change with low impact right now I would not recommend making this change now, but if you cut a major in the future I would look at surfacing these errors and warnings as events on the main registry interface. That way platforms like NQ can still log valuable events but will have more control over it without having to PR changes like this to the lib.

fix: downgrade timeout error to debug log

---

.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml

Also, remove the node-16 version from the test matrix, because it hangs
during the npm install step with no output. Not sure how to fix this, so
we'll just skip it for now.

install dependencies for github actions

---

src/bucket_counter.js
test/bucket_counter.test.js

Add `increment` method to BucketCounter to allow for
batch increments of the same amount. Consistent with
interface for Java implementation (Netflix/spectator#950).

batch increment for BucketCounter

---

types/registry.d.ts

Current typings for hrtime require an argument. However, the implementation actually does not.
See other open source hrtime typings:
https://sourcegraph.com/github.com/DefinitelyTyped/DefinitelyTyped/-/blob/types/node/process.d.ts?L118:13

Update types for hrtime to match Node.process

---

package.json
src/meter/timer.ts
test/meter/timer.test.ts

Restore the ability to pass process.hrtime() directly to the record method, because this is the simplest way to record latency durations.

adjust timer record method

---

package.json
src/meter/percentile_timer.ts
test/meter/percentile_timer.test.ts

Add the ability to pass process.hrtime() directly to the record method, because this is the simplest way to record latency durations. This keeps the usage similar to timers.

adjust percentile timer record method

---

package.json
src/config.ts
src/writer/file_writer.ts
src/writer/new_writer.ts
test/config.test.ts

The `unix_gram` module was removed from the standard library in 2011, for Windows portability reasons, so this library will not support Unix Domain Sockets.
https://github.com/nodejs/node/issues/29339
There is a third-party library `unix-dgram`, which offers this functionality, but it introduces some complications, and we want this library to be as low- friction as possible. Thus, we will not adopt this module.
https://github.com/bnoordhuis/node-unix-dgram
This state of affairs is similar to the Java thin-client, where the JVM does not support Unix Domain Sockets until 16+:
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/UnixDomainSocketAddress.html).

remove references to unix domain sockets
